local L = AceLibrary("AceLocale-2.2"):new("BugSack")

L:RegisterTranslations("esES", function() return {
	-- Command descriptions
	["Show sack"] = "Mostrar el saco",
	["Show errors in the sack."] = "Muestra los errores en el saco.",
	["Current error"] = "Error actual",
	["Show the current error."] = "Muestra el error actual.",
	["Current session"] = "Sesi\195\179n actual",
	["Show errors from the current session."] = "Muestra los errores de la sesi\195\179n actual",
	["Previous session"] = "Sesi\195\179n previa",
	["Show errors from the previous session."] = "Muestra los errores de la sesi\195\179n previa.",
	["By session number"] = "Por n\195\186mero de sesi\195\179n",
	["Show errors by session number."] = "Muestra los errores por el n\195\186mero de sesi\195\179n.",
	["All errors"] = "Todos los errores",
	["Show all errors."] = "Muestra todos los errores",
	["Received errors"] = "Errores recibidos",
	["Show errors received from another player."] = "Muestra los errores recibidos desde otro jugador",
	["Send bugs"] = "Enviar errores",
	["Sends your current session bugs to another BugSack user."] = "Envía los errores de tu sesión actual a otro usuario. Solo funciona si tanto tú como el receptor tiene una instancia de AceComm-2.0 y BugSack cargadas.",
	["<player name>"] = "<nombre del jugador>",
	["Menu"] = "Menú",
	["Menu options."] = "Menú de opciones",

	["List errors"] = "Mostrar lista de errores",
	["List errors to the chat frame."] = "Muestra la lista de errores en la ventana de chat.",
	["List the current error."] = "Mostrar lista de errores actuales",
	["List errors from the current session."] = "Mostrar lista de errores de la sesi\195\179n actual",
	["List errors from the previous session."] = "Mostrar errores de la sesi\195\179n previa",
	["List errors by session number."] = "Mostrar lista de errores por n\195\186mero de sesi\195\179n",
	["List all errors."] = "Mostrar lista con todos los errores",
	["List errors received from another player."] = "Mostrar una lista de los errores recibidos desde otro jugador",

	["Auto popup"] = "Ventana emergente automática",
	["Toggle auto BugSack frame popup."] = "Activa la ventana emergente de BugSack.",
	["Chatframe output"] = "Mostrar en chat",
	["Print a warning to the chat frame when an error occurs."] = "Muestra un aviso en la ventana de chat cuando ocurre un error.",
	["Errors to chatframe"] = "Errores en chat",
	["Print the full error message to the chat frame instead of just a warning."] = "Muestra el mensaje de error completo en la ventana de chat en vez de solo un aviso",
	["Sound"] = "Sonido",
	["What sound to play when an error occurs (Ctrl-Click to preview.)"] = "Qué sonido se reproducirá cuando ocurra un error (Ctrl-Clic para previsualizar)",
	["Mute"] = "Enmudecer",
	["Toggle an audible warning everytime an error occurs."] = "Determina si se reproduce un aviso auditivo cada vez que ocurre un error.",
	["Save errors"] = "Guardar errores",
	["Toggle whether to save errors to your SavedVariables\\!BugGrabber.lua file."] = "Determina si se graban los errores en tu archivo SavedVariables\\!BugGrabber.lua",
	["Limit"] = "L\195\173mite",
	["Set the limit on the nr of errors saved."] = "Establece el l\195\173mite de la cantidad de errores guardados.",
	["Filter addon mistakes"] = "Filtrar errores de accesorio",
	["Filters common mistakes that trigger the blocked/forbidden event."] = "Filtra errores comunes que hacen saltar el evento de bloqueado/prohibido.",
	["Throttle at excessive amount"] = "Acelerar cuando demasiados",
	["Whether to throttle for a default of 60 seconds when BugGrabber catches more than 20 errors per second."] = "Determina si se acelera a 60 segundos por defecto cuando BugGrabber intercepta más de 20 errores por segundo.",

	["Generate bug"] = "Generar error",
	["Generate a fake bug for testing."] = "Genera un error falso para hacer pruebas.",
	["Script bug"] = "Error de script",
	["Generate a script bug."] = "Genera un error de script",
	["Addon bug"] = "Error de accesorio",
	["Generate an addon bug."] = "Genera un error de accesorio.",

	["Clear errors"] = "Borrar errores",
	["Clear out the errors database."] = "Borra los errores de la base de datos.",

	["%d sec."] = "%d seg.",
	["|cffeda55fBugGrabber|r is paused due to an excessive amount of errors being generated. It will resume normal operations in |cffff0000%d|r seconds. |cffeda55fDouble-Click|r to resume now."] = "|cffeda55fBugGrabber|r se ha parado debido a que se han generado una cantidad excesiva de errores. Volverá a funcionar normalmente en  |cffff0000%d|r segundos. Haz |cffeda55fdoble-Clic|r para continuar ahora.",

	-- Chat messages
	["You have no errors, yay!"] = "No tienes errores, ¡chachi!",
	["List of errors:"] = "Lista de errores:",
	["An error has been generated."] = "Se ha generado un error.",
	["BugSack generated this fake error."] = "BugSack ha generado este falso error.",
	["All errors were wiped."] = "Todos los errores fueron limpiados.",
	["An error has been recorded."] = "Se ha guardado un error.",
	["%d errors have been recorded."] = "%d errores han sido guardados.",
	["You've received %d errors from %s, you can show them with /bugsack show received."] = "Has recibido %d errores desde %s, puedes mostrarlos con '/bugsack show received'",
	["%d errors has been sent to %s. He must have BugSack to be able to read them."] = "%d errores han sido enviados a %s. Si no tiene tanto BugSack como AceComm-2.0 no podrá leerlos.",

	-- Frame messages,
	[" (... more ...)"] = " (... m\194\191s ...)",
	["No errors found"] = "No se han encontrado errores",
	["Error %d of %d"] = "Error %d de %d",
	[" (viewing last error)"] = " (viendo el \195\186ltimo error)",
	[" (viewing session errors)"] = " (viendo los errores de la sesi\195\179n)",
	[" (viewing previous session errors)"] = " (viendo los errores de sesiones previas)",
	[" (viewing all errors)"] = " (viendo todos los errores)",
	[" (viewing errors for session %d)"] = " (viendo errores para la sesi\195\179n %d)",
	[" (viewing errors from %s)"] = " (viendo errores desde %s)",

	-- FuBar plugin
	["|cffeda55fClick|r to open BugSack with the last error. |cffeda55fShift-Click|r to reload the user interface. |cffeda55fAlt-Click|r to clear the sack."] = "|cffeda55fClic|r para abrir BugSack con el \195\186ltimo error. |cffeda55fMay\195\186sculas-Clic|r para recargar la interfaz de usuario. |cffeda55fAlt-Clic|r para limpiar el saco.",
} end)

